name: llmge-env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12.9
  - pip
  - numpy=2.2.2
  - cudnn=9.1.1.17
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - torchaudio=2.5.1
  - torchvision
  - transformers
  - pyyaml
  - fastapi
  - uvicorn
  - pydantic
  - pip:
      - accelerate
      - flash-attn
      - deap
      - huggingface-hub
      - hydra-core
      - einops
      - tokenizers
      - sympy
      - starlette
      - regex
      - annotated-types
      - click
      - anyio
      - h11
      - safetensors
      - networkx
      - psutil
      - triton