# Large Language Model Guided Evolution 
# Info Specification

# constants.py
# Example
root_directory : 
# Example
data_path : 
# Example
sota_root : 
# Example
seed_network : 
# Example
local_device : 
# Example
mac_os : 
# Example
llm_model : 
# Example
llm_model_path : 

# Evolution | Constants | Parameters | Defaults
fitness_weights : 
invalid_fitness_max : 
place_holder_fitness : 
num_elites : 
generations : 
probability_Quality_Control : 
probability_EOT : 
number_of_generations : 
starting_population_size : 32
population_size : 8
cross_over_probability : 0.35
mutation_probability : 0.8
number_of_elites : 44
hof_size : 100
Quality_Control_Boolean : False
Hugging_Face_Boolean : False

# mixt.sh
source_code_file_path :  
source_gene_file_path_x : 
source_gene_file_path_z : 

# run_improved
repository_path : 
data_path : 
sota_path : 
seed_path : 
output_path : 
train_entry : 
fitness_weights : 
start_population_size :