configurations:
  epoch: 1000
  bs: 192
  optimizer: "sgd"
  init_lr: 0.1
  lr_df: 0.7
  end_lr: 0.01
  wd: 1e-4
  imgsz: 224
  val_r: 0
  worker: 8
  seed: None
  network : "network"

results:
 cifar-10: 
  params: 0.51M
  train-loss: 0.0011
  train_acc: 0.9999
  val_loss: 0.2762
  val-acc: 0.9329
  test-loss: 0.3087
  test-acc: 0.9252

info:
  one: "Change the initial learning rate to higher value (0.1)"
  two: "Change the step-down factor of lr rate to higher value (0.7)"
